### ISSUE TITLE
FYI inlined fns (and added as contributor)

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nonmem2rx#11]
Hi @philipdelff

FYI, I changed and inline and modified the functions here:

https://github.com/nlmixr2/nonmem2rx/blob/main/R/nmtab.R

https://github.com/nlmixr2/nonmem2rx/blob/main/R/readCov.R

I mentioned you as an author and added you as a contributor

The one above should probably make it in some version back to your excellent `NMdata` since reading the theta matrix can be used to simulate clinical trials with uncertainty.

**Comment by philipdelff** [comment]
Thanks @mattfidler,

Let me know if I can be of any further help. NMdata could have more of interest - as is or after a bit of modification. Happy to discuss.

Best,
Philip

**Comment by mattfidler** [comment]
Sure,  the only modification I have to make it more general is to drop the first column (optionally). 

This is to allow your reader to handle nonmem's '.cov' files.

I have a pull request


https://github.com/philipdelff/NMdata/pull/41

If you want to discuss there, that is fine.

These are needed to simulate with uncertainty in your parameter estimates with `rxode2` and other sorts of packages.

This package allows automatic translation of NONMEM to `rxode2`, while validating the model is giving the correct results.  The information will be read in and will allow simulation with uncertainty if you wish it.
