### ISSUE TITLE
Covariate detection adds too many covariates

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nonmem2rx#113]
First, this was very helpful to convert a NONMEM model into an rxode2 model with minimal effort.  Thanks!

I have a model (which unfortunately, I cannot share) that has a few oddities with covariate detection that may be possible to debug without the full model:

When I determine what the covariates in the model, I get a much longer list than expected:

```
model$allCovs
# [1] "WT"      "rxddta1" "rxddta2" "rxddta3" "TYPE"    "eps1"    "DV"     
```

I expected `WT` and `TYPE` because they are used as parts of the model itself.  I did not expect the others.

`eps1` appears to come from `Y = IPRED+ERR(1)*W` (where `IPRED` and `W` are defined above this line).
I expected that to become:
```
y = ipred
y ~ add(w)
```
or some other sigma-type definition.

`rxddta1`, `rxddta2`, `rxddta3` don't appear in the generated model, so I'm not sure why they exist.  The closest that I see suggests that they may come from the following:

In the original model:

```
A_0(1) = 0
A_0(2) = 0
A_0(3) = 0
```

becomes

```
rxini.rxddta1. <- 0
rxddta1(0) <- rxini.rxddta1.
rxini.rxddta2. <- 0
rxddta2(0) <- rxini.rxddta2.
rxini.rxddta3. <- 0
rxddta3(0) <- rxini.rxddta3.
```

Or in the original model:

```
F1=(EXP(TVF1+ETA(6))/(1+EXP(TVF1+ETA(6)))*1)
```

becomes

```
rxf.rxddta1. <- (exp(tvf1 + e.eta6)/(1 + exp(tvf1 + e.eta6)) * 1)
```

**Comment by mattfidler** [comment]
- Are you using a solved system?
- `rxddta` represents the differential compartments, are these missing?

**Comment by mattfidler** [comment]
The `eps1` is  covariate but the `eps1` is stored in the ui object, you can see it with `ui$sigma`

**Comment by mattfidler** [comment]
It is harder to debug with out a model, I just noticed that you said that `eps1` isn't in the model.  In theory it is removed from the model when the following translation is made:

```
y = ipred
y ~ add(w)
```

**Comment by billdenney** [comment]
1. Yes, I'm using a solved system (by which I mean I'm starting from the .lst file).
2. The differential equation compartments are present, and they appeared to be defined correctly.
3. The translation to `y = ipred; y ~ add(w)` was not made.  I think that this is because it was within an `if` block.  There was no dependent variable defined in the generated model.

**Comment by mattfidler** [comment]
My guess is that  you are using an updated version of `rxode2`, but not one that includes the rename fix.

If you were using the CRAN rxode2, this should work:

5bea320bb9dd82874acde094c57f85128a68ce34

If you were using the github rxode2 you need to include the github revision


https://github.com/nlmixr2/rxode2/commit/020e2ae541f0cdff05a7f558d11ac488467fbd4e

Otherwise the initial conditions are not renamed to the correct names in your NONMEM file (or input options)

This is why you have the lines:

```
rxini.rxddta1. <- 0
rxddta1(0) <- rxini.rxddta1.
rxini.rxddta2. <- 0
rxddta2(0) <- rxini.rxddta2.
rxini.rxddta3. <- 0
rxddta3(0) <- rxini.rxddta3.
```

**Comment by mattfidler** [comment]
As said before, this is not a complete `nlmixr2` translation, but a `rxode2` translation, so don't expect the residual to be adapted in this case (sorry).  Sometimes it is (sometimes it isn't).  But it still allows simulation from the model and with a little manual editing you should be able to do.  The `eps1` is captured in the modified ui so you can simulate with the model.

**Comment by billdenney** [comment]
The amount of editing required was truly minimal.  It was an amazing help even with these questions.  I'll try the new `rxode2` tomorrow.

**Comment by mattfidler** [comment]
If you have any more problems, please let me know.

However, I think this is not an issue with the right version of rxode2.
