### ISSUE TITLE
Allow comparison of manually created UI to nonmem2rx ui

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nonmem2rx#114]
The amount of editing required was truly minimal.  It was an amazing help even with these questions.  I'll try the new `rxode2` tomorrow.

_Originally posted by @billdenney in https://github.com/nlmixr2/nonmem2rx/issues/113#issuecomment-1506159466_
            
As a user I would like to make some manual edits to the rxode2 model and then compare to the original model to make sure it still works in the same way, (ie add pred/ipred comparison).

If these manual edits validate, and it is a fully qualified nlmixr2 model, I would like to be able to turn it into a full nlmixr2 fit.

**Comment by billdenney** [comment]
Ooh, good idea.

One complexity of some of the edits that I made was that I simplified many of the parameter names.  My guess is that the most important parameter names that I changed were the etas.

I assume that if I did this using `rename()` then it could be tracked readily.  If I did it some other way, then some mapping would need to be applied.
