### ISSUE TITLE
Parse error for data with character equality test

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nonmem2rx#140]
I have a NONMEM .lst file with the following in the $DATA section which caused a parse error:

```
$DATA syntax error:
:002:             IGNORE=(C='C', TIME.LT.0, DVID.EQ.1, DVID.EQ.3,
                            ^
:002: 
:003:             CYCL.EQ.99)
```

(I didn't know that you could do character equality tests before this.)

**Comment by mattfidler** [comment]
The equality test is included.  However, the `'C'` was not understood by the parser.

**Comment by mattfidler** [comment]
Should be fixed

**Comment by billdenney** [comment]
Yep, it works now.
