### ISSUE TITLE
Hi @philipdelff

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nonmem2rx#157]
Hi @philipdelff 

Thanks for your patience, for the `model<-` to work  you need at least rxode2 2.0.12.  I forgot to add that explicitly as a dependency .

Matt

_Originally posted by @mattfidler in https://github.com/nlmixr2/nonmem2rx/issues/156#issuecomment-1622790994_

**Comment by philipdelff** [comment]
Thanks @mattfidler
