### ISSUE TITLE
Simplification in nmcov

### ISSUE THREAD

**Issue by philipdelff** [nlmixr2/nonmem2rx#162]
Is there a test where this happens in readcov?
    if (grepl(", *OMEGA\\( *1 *, *1\\)", colnames)){
...
} 
I can simplify the handling of it but I want to make sure it's tested before I make a pull request.

**Comment by mattfidler** [comment]
It is tested in the NONMEM tutorials files. To test them in CI/CD remove the zip files from the .Rbuildignore file.  They will need to be ignored in the resubmission to CRAN since it makes the package over 3 MG

**Comment by mattfidler** [comment]
I also noticed the ci/cd is broken.  I needs to grab the lastet nlmixr development stack.  I found some differences and have implemented some options in rxode2 to handle the rxode2 and NONMEM differences.
