### ISSUE TITLE
Parse error for data ignore statement with numerical equality test

### ISSUE THREAD

**Issue by PharmetheusHenrikN** [nlmixr2/nonmem2rx#173]
Hi there! I noticed an issue for models with numerical comparison instead of character comparison (`.EQN.`) in the $DATA ignore statements:

```
$DATA syntax error:
:002:             IGNORE=@ IGNORE(BLQ.EQN.1)
                                     ^
```
I assume there needs to be an `eqn_expression_nm` defined in the C.

**Comment by mattfidler** [comment]
Ah, you say it is for numerical comparison.  I must say that `.eq.` works for character comparison and numeric comparison in NONMEM so I didn't know there was another operator.  

I will add this to the grammer.

**Comment by mattfidler** [comment]
Fixed in edded16

**Comment by mattfidler** [comment]
I also see you mention `eqn_expression_nm` which is where it is changed in the grammar files.

Note by simply doing `devtools::document()` it updates the C for simple fixes like this one.

**Comment by PharmetheusHenrikN** [comment]
That's excellent, thank you for the fast turnaround!

**Comment by mattfidler** [comment]
No problem
