### ISSUE TITLE
Question: Should fit models become `nlmixr2est` objects instead of `rxode2` objects?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nonmem2rx#25]
It seems like one scenario could be that you're bringing in the control stream, alone.  Another scenario could be that you're bringing in the entire fit.

In the control-stream-only scenario, an `rxode2` UI object makes sense.  In the entire-fit scenario, it seems like a full `nlmixr2est` fit (similar to what is done with `babelmixr2`) would be better.

Is the plan to make that feasible within babelmixr2 and this would become a suggested dependency there?

**Comment by mattfidler** [comment]
No.  There would have to be some sort of manual intervention.  There would be a cyclic dependency.

**Comment by billdenney** [comment]
Okay
