### ISSUE TITLE
Should nonmem information be retained during piping?

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nonmem2rx#52]
you are changing the model...

**Comment by billdenney** [comment]
If you're just adding labels, I don't think so.  But for everything else, yes.

Since label changing is a niche feature, I lean toward the simplicity of dropping the NONMEM info.

**Comment by mattfidler** [comment]
It is already been added, but it could be an option to add/remove at the user's discretion.

**Comment by mattfidler** [comment]
https://github.com/nlmixr2/nonmem2rx/pull/48

**Comment by mattfidler** [comment]
`sigma` should at least be maintained since it isn't part of the `rxode2` ui unless it is a full `nlmixr2` model

**Comment by mattfidler** [comment]
Maybe the `ini` should be extended to change values of `eps` within the `sigma`....
