### ISSUE TITLE
installation unsuccessful

### ISSUE THREAD

**Issue by yoshihirokuroki** [nlmixr2/nonmem2rx#80]
Dear contributers,
Good Day
I am trying to install nonmem2rx in the project folder with renv 0.16.0 in macOS Ventura 13.2.1 running on intel Core i5 but installation was unsuccessful. 
Error messages were captured an shown below:

```
abbrec.c:9:10: fatal error: 'dparser2.h' file not found
#include <dparser2.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [abbrec.o] Error 1
ERROR: compilation failed for package ‘nonmem2rx’
```

Did I do anything wrong?

Kind regards,
Yoshi

**Comment by mattfidler** [comment]
Indeed it needs more recent version of many packages.

Until it is on CRAN this is (by definition) still being developed.

You can try it out quickly, however, by the following:

```r
install.packages(c("dparser", "rxode2ll", "rxode2parse",
                   "rxode2random", "rxode2et", "rxode2", "nonmem2rx"),
                 repos=c(nlmixr2="https://nlmixr2.r-universe.dev",
                         CRAN="https://cloud.r-project.org"))
```

Or if `nonmem2rx` in not on r-universe yet, try:

```r
install.packages(c("dparser", "rxode2ll", "rxode2parse",
                   "rxode2random", "rxode2et", "rxode2"),
                 repos=c(nlmixr2="https://nlmixr2.r-universe.dev",
                         CRAN="https://cloud.r-project.org"))

remotes::install_github("nlmixr2/nonmem2rx")
```

**Comment by mattfidler** [comment]
You may have to install the rest of the `nlmixr2` packages if you intend to run `nlmixr2` as well.

**Comment by yoshihirokuroki** [comment]
Hi @billdenney and @mattfidler 
Following Matt's guidance https://github.com/nlmixr2/nonmem2rx/issues/80#issuecomment-1460759224 , I could install nonmem2rx and confirm that the demo code in README works successfully.
Many many thanks!
Yoshi
